# Video: Handling Arrays of Different Shapes

This video introduces NumPy's handling of arrays with different shapes.
Combining arrays with individual scalars have a simple intuitive behavior.
Broadcasting generalizes that behavior in a powerful way.

Script:
* We looked at some examples of NumPy working with multiple arrays at once, and combining their data.
* All the examples before used arrays of the same shape.
* This let us describe the computation based on numbers with the same index being combined.
* NumPy can handle more array combinations than this.
* The simplest case is combining an array with a scalar.

In [ ]:
import numpy as np

x = np.array([[0, 1, 2, 3, 4, 5]])
x

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
x + 10

array([[10, 11, 12, 13, 14]])

Script:
* If you combine an array with a scalar, we say that scalar is broadcast and combined with every number in the array.
* This works with other dimensions too.

In [ ]:
y = np.array([[0], [100], [200], [300], [400]])
y

array([[  0],
       [100],
       [200],
       [300],
       [400]])

In [ ]:
x + y

array([[  0,   1,   2,   3,   4,   5],
       [100, 101, 102, 103, 104, 105],
       [200, 201, 202, 203, 204, 205],
       [300, 301, 302, 303, 304, 305],
       [400, 401, 402, 403, 404, 405]])

Script:
* This just combined `x` with 1 row of 6 columns, with `y` with 5 rows of 1 column.
* The result had 5 rows and 6 columns.
* If you look at the output values, you can see that the values were adding an `x` value from the same column with a `y` value from the same row.
* How did this work?
* First, let's look at the shapes of `x` and `y`.

In [ ]:
x.shape

(1, 6)

In [ ]:
y.shape

(5, 1)

Script:
* Those shapes definitely do not match, but for both axes, one of the arrays has a length 1 for that axis.
* Informally, broadcasting will work if for each axis, both arrays have the same length or at least one of them has length 1.
* Then the output shape will be the shared or non-zero length for each axis.
* So shapes 1 and 6 combined with 5 and 1 produced shape 5 and 6.

In [ ]:
(x + y).shape

(5, 6)

Script:
* After determining the shape, you can imagine the NumPy algorithm looping every set of indexes in the output and grabbing input values from each side.
* When it grabs the input from each side, it adjusts the index to zero out and ignore the axes where that side only has length 1.
* Let's look at those numbers again.

In [ ]:
x

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
y

array([[  0],
       [100],
       [200],
       [300],
       [400]])

In [ ]:
x + y

array([[  0,   1,   2,   3,   4,   5],
       [100, 101, 102, 103, 104, 105],
       [200, 201, 202, 203, 204, 205],
       [300, 301, 302, 303, 304, 305],
       [400, 401, 402, 403, 404, 405]])

Script:
* Since all the x values are below ten, and all the y values are multiples of a hundred, you can look at any entry of x + y and see which x and y values were added together.
* The first column always used value 0 from the x side.
* That is because x has length 1 in the first axis, the row axis.
* So the one row of x was repeatedly used for each row of the output.
* The second column always used value 1 from the x side.
* The third column always used value 2, and so on.
* Similarly, the y array has length 1 for the second axis.
* y has just one column.
* So the one column of y was repeatedly used for each column of the output.
* That is the basic gist of how broadcasting works.
* There are a few more rules to get a full description, particularly for arrays with different dimensions.
* The NumPy documentation for broadcasting is pretty good, and has some nice illustrations of the process.
* That documentation is linked in the resources section after this video.
* One last comment about broadcasting.
* We saw that we could combine a one row array with a one column array, and get an array with all combinations of their values.
* That means that we got an output whose size was the product of the input sizes.
* Which can be very powerful.
* But also very big in memory usage and time to compute.
* So use it when it matches your problem, but don't go overboard, especially if you won't be keeping the result.