## **Week 8 Examples**

<li>Array slicing syntax
<li>Reshaping
<li>Row-wise vs Column-wise opeations
<li>Dot-product example: Weighted average
<li>Monte carlo simulation

In [18]:
import numpy as np

# create an array of 30 values:
x = np.arange(30)
# print('x =', x)

#'shape' describes the dimension of an array:
print('x.shape = ', x.shape)

# re-shape the array:
x = x.reshape((5,6))

# print('x.shape = ', x.shape)
print('x =') # label
print(x) # array

# indexing: element-access:
# x[4] = 99
# print('x[4] = ')
# print(x[4]) # returns one row of the array

print('x[2:4] = ')
print(x[2:4]) # slice multiple rows

# print('x[:, 3] =')
# print(x[:, 3]) # slice column 3

print('x[2:4, 3:5] = ')
print(x[2:4, 3:5]) # slice 2 rows and 2 cols

x.shape =  (30,)
x =
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
x[2:4] = 
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
x[2:4, 3:5] = 
[[15 16]
 [21 22]]


Looping through columns

In [23]:
a = np.arange(1, 21).reshape((4,5))
print(a)

# loop through columns with slicing:
for j in range(a.shape[1]): # shape[1] is the number of columns

    # slice out all rows, col j
    col = a[:,j]
    print(f'col {j} = {col}')


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
col 0 = [ 1  6 11 16]
col 1 = [ 2  7 12 17]
col 2 = [ 3  8 13 18]
col 3 = [ 4  9 14 19]
col 4 = [ 5 10 15 20]


Reshaping and broadcast operators

In [ ]:
a = np.arange(10,20,2)
b = np.arange(90,100)
print(f'a = {a}')
print(f'b = {b}')

a = a.reshape((5,1)) # this will create a 5x1 array
print(f'a = {a}')

# now we can apply the + operator
c = a + b
print(f'c = {c}')

a = [10 12 14 16 18]
b = [90 91 92 93 94 95 96 97 98 99]
a = [[10]
 [12]
 [14]
 [16]
 [18]]
c = [[100 101 102 103 104 105 106 107 108 109]
 [102 103 104 105 106 107 108 109 110 111]
 [104 105 106 107 108 109 110 111 112 113]
 [106 107 108 109 110 111 112 113 114 115]
 [108 109 110 111 112 113 114 115 116 117]]


Row-wise and column-wise operations

In [ ]:
x = np.random.randint(1, 100, size=24)
# print(f'x = {x}')
x = x.reshape((4,6))
print(f'x =\n{x}')

# show aggregate functions: sum, min, max, mean, std, median
print('x.min() = ',x.min())

# axis=0 means "column-wise"
print(f'x.min(axis=0) =', x.min(axis=0))

# axis=1 means "row-wise"
# print(f'x.min(axis=1) =', x.min(axis=1))
print(f'x.min(axis=1) =\n', x.min(axis=1).reshape(x.shape[0],1))

x =
[[ 3  3 90 80 81 66]
 [12 46 24 99 79 52]
 [40 48 92 96  9 69]
 [94 57 50  3 17 79]]
x.min() =  3
x.min(axis=0) = [ 3  3 24  3  9 52]
x.min(axis=1) =
 [[ 3]
 [12]
 [ 9]
 [ 3]]


Some other methods: flatten ravel


In [ ]:
x = np.arange(24).reshape((4,6))
# x[0,0] = 99
print(f'x = \n{x}')

# ravel is a function on the numpy library
y = np.ravel(x) # create a 1-d view of the array
y[0] = 99
print(f'y = \n{y}')
print(f'x = \n{x}')

# a contrasting example:
# flatten is a method on the numpy.ndarray class
z = x.flatten() # flatten creates a whole new array, in 1d
z[-1] = 42
print(f'z = \n{z}') # change an element in z
print(f'x = \n{x}') # it does not change the underlying data in x


x = 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
y = 
[99  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
x = 
[[99  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
z = 
[99  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 42]
x = 
[[99  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


Linear algebra: example weighted average

In [ ]:
# consider a portfolio of 3 loans/investments
loans = np.array([54000, 127000, 222999])
rates = np.array([0.075, 0.052, 0.125])

print(f'loans = {loans}')
print(f'rates = {rates}')

# how much interest for each loan:
interest = loans * rates
print(f'interest = {interest}')
print(f'total interest = {interest.sum()}')

# what percentage in each loan?
weights = loans / loans.sum()
print(f'weights = {weights}')

# wacc: weighted-average cost of capital
wacc = weights @ rates # dot-product
print(f'wacc = {wacc}')



loans = [ 54000 127000 222999]
rates = [0.075 0.052 0.125]
interest = [ 4050.     6604.    27874.875]
total interest = 38528.875
weights = [0.1336637  0.31435721 0.55197909]
wacc = 0.09536873853648152


Monte-carlo simulation: estimate the value of pi

In [ ]:
import random # plain python random library
import time

throws = 10000000
hits = 0 # number we land a dart inside the circle

# (1) plain python way
print("The 'plain python' way:")
bt = time.time() # begin time
for i in range(1,throws+1):

    # pick random coordinates:
    x = random.random()
    y = random.random() 

    # check if (x,y) is inside the circle:
    if (x ** 2 + y ** 2) <= 1:
        hits = hits + 1

estpi = 4 * hits / i

et = time.time() # end time
print(f"hits={hits}/throws={i}, estpi={estpi}")
print(f'with n={throws}, elapsed time = {et-bt} seconds')

# (2) same thing, using numpy methods
print("The 'numpy way':")
bt = time.time() # begin time

# each is an array of 100,000,000 items
x = np.random.random(throws)
y = np.random.random(throws)

# count the hits:
hits = ((x ** 2 + y ** 2) <= 1).sum()
estpi = 4 * hits / throws

et = time.time() # end time
print(f"hits={hits}/throws={i}, estpi={estpi}")
print(f'with n={throws}, elapsed time = {et-bt} seconds')

hits=7854542/throws=10000000, estpi=3.1418168
with n=10000000, elapsed time = 4.627824068069458 seconds
hits=7855536/throws=10000000, estpi=3.1422144
with n=10000000, elapsed time = 0.2550232410430908 seconds
