Array slicing syntax/examples

In [ ]:
import numpy as np
# create an array of 30 values
x = np.arange(30)
x = x.reshape((5,6))
print('x = ')
print(x)
# # indexing
# print('x[4] = ')
# print(x[4])
# 
# print('x[2:4] = ') # slicing: multiple rows
# print(x[2:4])
## slicing: columns:
# print('x[ :, 3:4 ] = ')
# print(x[ :, 3:4 ]) # slicing all rows, one column
# print('x[ :, 3:5 ] = ')
# print(x[ :, 3:5 ]) # slicing all rows, select columns
print('x[ 2:4, 3:5 ] = ')
print(x[ 2:4, 3:5 ]) # slicing selected rows/columns


x = 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
x[ 2:4, 3:5 ] = 
[[15 16]
 [21 22]]


Example of reshaping 1-d arrays into row/column vectors so that + applies by broadcasting

In [ ]:
import numpy as np
a = np.arange(10, 20, 2)
b = np.arange(90, 100)
# print( a + b ) # woah! that didn't work; shapes (5,) + (10,)

# reshape array a:
# a = a.reshape((5,1)) # created a column vector (2-dim): 5x1
a = a[ :, None ] # slicing all elements into separate rows
print('a = ')
print(a)
print('b = ')
print(b)
print('a + b =')
print( a + b )


a = 
[[10]
 [12]
 [14]
 [16]
 [18]]
b = 
[90 91 92 93 94 95 96 97 98 99]
a + b =
[[100 101 102 103 104 105 106 107 108 109]
 [102 103 104 105 106 107 108 109 110 111]
 [104 105 106 107 108 109 110 111 112 113]
 [106 107 108 109 110 111 112 113 114 115]
 [108 109 110 111 112 113 114 115 116 117]]


Discuss array column-wise vs row-wise operations

In [ ]:
import numpy as np
x = np.random.randint(1, 100, size=24)
print('x = ')
print(x)
x = x.reshape((4,-1))
print('x = ')
print(x)
# print('x.min() =')
# print(x.min())
# # column-wise operations:
# print('x.min(axis=0) = ')
# print(x.min(axis=0))
# # row-wise operations:
# print('x.min(axis=1).reshape(4,-1) = ')
# print(x.min(axis=1).reshape(4,-1))
# print('x.min(axis=1).T = ')
# print(x.min(axis=1).T)
# a transpose of a 1-d array is still a 1-d array
y = np.array([x]) # create a 2-d array (row)
print('y.min(axis=1).T = ')
print(y.min(axis=1).T)


x = 
[33 88 64 53 98 82 93 82 55 35 40 91 12 49 45 28 29 86  7 50 21 39 11 24]
x = 
[[33 88 64 53 98 82]
 [93 82 55 35 40 91]
 [12 49 45 28 29 86]
 [ 7 50 21 39 11 24]]
y.min(axis=1).T = 
[[ 7]
 [49]
 [21]
 [28]
 [11]
 [24]]


np functions to discuss/examples:
- np.ravel
- np.flatten
- np.hstack, np.vstack

In [152]:
x = np.arange(24).reshape((4,6))
print('x = ')
print(x)
# y = np.ravel(x) # combine into a 1-d view
y = x.flatten() # return a new array in 1-d
print('y = ')
print(y)
y[0] = 99 # change one element
print('y = ')
print(y)
print('x = ')
print(x)



x = 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
y = 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
y = 
[99  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
x = 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


- time comparison of append vs create zeros and fill in values
- discuss view vs copy, performance characteristics
- monte carlo simulation (python vs numpy)



In [ ]:
import time
import random
# print(time.time()) # 1/1/1970 at 0:00:00

# filling up an array of elements:
# n = 100000000
# print(f'fill in {n:,} elements... with append') ### took about 2 seconds for 100,000 elements
# a = np.array([])
# bt = time.time() # record the time before this operation
# for i in range(n):
#     a = np.append(a, i)
# et = time.time() # record the time after this operation
# # print(a)
# print(f"Elapsed time was {et-bt} seconds.")

# # create an array of zeros, and fill in values:
# print(f'fill in {n:,} elements... with assignment')
# a = np.zeros(n)
# bt = time.time() # record the time before this operation
# for i in range(n):
#     a[i] = i
# et = time.time() # record the time after this operation
# #print(a)
# print(f"Elapsed time was {et-bt} seconds.")

# # create an array of zeros, and fill in values:
# print(f'fill in {n:,} elements... with np.arange(n)')
# bt = time.time() # record the time before this operation
# a = np.arange(n)
# et = time.time() # record the time after this operation
# #print(a)
# print(f"Elapsed time was {et-bt} seconds.")

# estimate pi by throwing darts
## (1) using a for loop and plain python arithmetic
throws = 10000000
hits = 0 # inside the circle
bt = time.time() # record the time before this operation
for i in range(throws):
    x = random.random()
    y = random.random()

    # check if (x,y) is inside the circle:
    if x ** 2 + y ** 2 <= 1:
        hits += 1
et = time.time() # record the time after this operation
est_pi = 4 * hits / throws
print(f'{hits} hits out of {throws} throws; est_pi = {est_pi}')
print(f"Elapsed time was {et-bt} seconds.")

## (2) the same operation, using numpy:
bt = time.time() # record the time before this operation
x = np.random.random(throws)
y = np.random.random(throws)
hits = (x ** 2 + y ** 2 <= 1).sum()
est_pi = 4 * hits / throws
et = time.time() # record the time after this operation
print(f'{hits} hits out of {throws} throws; est_pi = {est_pi}')
print(f"Elapsed time was {et-bt} seconds.")


7851972 hits out of 10000000 throws; est_pi = 3.1407888
Elapsed time was 4.512710094451904 seconds.
7854269 hits out of 10000000 throws; est_pi = 3.1417076
Elapsed time was 0.24307036399841309 seconds.
