# Video: Flattening Arrays with Views

This video covers the different choices and tradeoffs flattening multi-dimensional arrays back down to one dimension.




In [ ]:
import numpy as np

In [ ]:
x_contiguous = np.array([[0, 1, 2], [3, 4, 5]])
x_contiguous

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
x_contiguous.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [ ]:
def check(a):
    print("ID", id(a))
    print("DATA")
    print(a)
    if a.base is not None:
        print("BASE")
        print(a.base)
        print("BASE ID", id(a.base))
    print("C_CONTIGUOUS", a.flags["C_CONTIGUOUS"])
    print("OWNDATA", a.flags["OWNDATA"])
    print("STRIDES", a.strides)

check(x_contiguous)

ID 140020203873904
DATA
[[0 1 2]
 [3 4 5]]
C_CONTIGUOUS True
OWNDATA True
STRIDES (24, 8)


In [ ]:
check(np.reshape(x_contiguous, -1))

ID 140020203872080
DATA
[0 1 2 3 4 5]
BASE
[[0 1 2]
 [3 4 5]]
BASE ID 140020203873904
C_CONTIGUOUS True
OWNDATA False
STRIDES (8,)


In [ ]:
check(np.ravel(x_contiguous))

ID 140020168542032
DATA
[0 1 2 3 4 5]
BASE
[[0 1 2]
 [3 4 5]]
BASE ID 140020203873904
C_CONTIGUOUS True
OWNDATA False
STRIDES (8,)


In [ ]:
x_not_contiguous = x_contiguous[:,::2]
check(x_not_contiguous)

ID 140020168543664
DATA
[[0 2]
 [3 5]]
BASE
[[0 1 2]
 [3 4 5]]
BASE ID 140020203873904
C_CONTIGUOUS False
OWNDATA False
STRIDES (24, 16)


In [ ]:
check(np.reshape(x_not_contiguous, -1))

ID 140020168545488
DATA
[0 2 3 5]
BASE
[[0 2]
 [3 5]]
BASE ID 140020203872080
C_CONTIGUOUS True
OWNDATA False
STRIDES (8,)


In [ ]:
mystery_base = np.reshape(x_not_contiguous, -1).base
check(mystery_base)

ID 140020203872080
DATA
[[0 2]
 [3 5]]
C_CONTIGUOUS True
OWNDATA True
STRIDES (16, 8)


In [ ]:
check(np.ravel(x_not_contiguous))

ID 140020168545008
DATA
[0 2 3 5]
C_CONTIGUOUS True
OWNDATA True
STRIDES (8,)


In [ ]:
check(x_not_contiguous.flatten())

ID 140020168545008
DATA
[0 2 3 5]
C_CONTIGUOUS True
OWNDATA True
STRIDES (8,)


**Code Notes:**
* The NumPy function [`numpy.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html), referenced as `np.reshape`, returns a new array with the same data and a specified shape.
  * `reshape` returns a view whenever possible.
  * If you specify length -1 for one axis in the shape, NumPy will calculate that size for you based on the other sizes and the number of data elements.
* The NumPy function [`numpy.ravel`](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html) returns a 1-dimensional array with the same contents as the input, and guarantees that the array will be contiguous.
  * If possible, `ravel` will return a view.
* The NumPy ndarray method [`numpy.ndarray.flatten`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html) returns a copy of the array's data as a one-dimensional array.
  * `flatten` never attempts to return a view which distinguishes it from `numpy.reshape` and `numpy.ravel`.