# Video: Surprising View Transformations

This video shows off some more surprising data transformations that can be implemented with views.
The resulting arrays look much more different from original data than the examples that we have looked at so far, but still can be created instantly using views.


In [ ]:
import numpy as np

In [ ]:
x = np.arange(20).reshape(4, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
def check(a):
    print("SHAPE")
    print(a.shape)
    print("DATA")
    print(a)
    print("STRIDES")
    print(a.strides)

check(x)

SHAPE
(4, 5)
DATA
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
STRIDES
(40, 8)


In [ ]:
check(np.transpose(x))

SHAPE
(5, 4)
DATA
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
STRIDES
(8, 40)


In [ ]:
check(x.T)

SHAPE
(5, 4)
DATA
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
STRIDES
(8, 40)


In [ ]:
check(np.flipud(x))

SHAPE
(4, 5)
DATA
[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
STRIDES
(-40, 8)


In [ ]:
check(np.fliplr(x))

SHAPE
(4, 5)
DATA
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]
STRIDES
(40, -8)


In [ ]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
check(np.lib.stride_tricks.sliding_window_view(x, (2, 2)))

SHAPE
(3, 4, 2, 2)
DATA
[[[[ 0  1]
   [ 5  6]]

  [[ 1  2]
   [ 6  7]]

  [[ 2  3]
   [ 7  8]]

  [[ 3  4]
   [ 8  9]]]


 [[[ 5  6]
   [10 11]]

  [[ 6  7]
   [11 12]]

  [[ 7  8]
   [12 13]]

  [[ 8  9]
   [13 14]]]


 [[[10 11]
   [15 16]]

  [[11 12]
   [16 17]]

  [[12 13]
   [17 18]]

  [[13 14]
   [18 19]]]]
STRIDES
(40, 8, 40, 8)


**Code Notes:**
* This video was meant to show you the variety of transformations that can be done instantly with views.
* You do not need to learn all these functions now, but here is a list of the functions just used or referenced if you are curious to read more about them.
  * [`numpy.transpose`](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html)
  * [`numpy.moveaxis`](https://numpy.org/doc/stable/reference/generated/numpy.moveaxis.html)
  * [`numpy.swapaxes`](https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html)
  * [`numpy.flipud`](https://numpy.org/doc/stable/reference/generated/numpy.flipud.html)
  * [`numpy.fliplr`](https://numpy.org/doc/stable/reference/generated/numpy.fliplr.html)
  * [`numpy.lib.stride_tricks.sliding_window_view`](https://numpy.org/doc/stable/reference/generated/numpy.lib.stride_tricks.sliding_window_view.html)
