# Video: Peeking at NumPy Array Layouts

This video looks at the underlying array layouts of two and three dimensional arrays to improve your intuition about how they work.

In [ ]:
import numpy as np

x = np.array([[0, 1, 2, 3], [100, 101, 102, 103], [200, 201, 202, 203]])
x

array([[  0,   1,   2,   3],
       [100, 101, 102, 103],
       [200, 201, 202, 203]])

In [ ]:
x[0]

array([0, 1, 2, 3])

In [ ]:
x[1]

array([100, 101, 102, 103])

In [ ]:
x[2]

array([200, 201, 202, 203])

In [ ]:
x_1d = np.ravel(x)
x_1d

array([  0,   1,   2,   3, 100, 101, 102, 103, 200, 201, 202, 203])

In [ ]:
x_1d[2] = 999
x

array([[  0,   1, 999,   3],
       [100, 101, 102, 103],
       [200, 201, 202, 203]])

In [ ]:
y = np.arange(27)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
y = y.reshape((3, 3, 3))
y

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
y[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
y[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
y[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

**Code Notes:**
* The NumPy function [`numpy.ravel`](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html), referenced as `np.ravel`, returns a contiguous 1-dimensional view of the input array.
  * If possible, it returns a view of the input array, so the underlying data is shared.
  * We will learn more about views in the next lesson.