# Video: Peeking at NumPy Array Layouts

This video looks at the underlying array layouts of two and three dimensional arrays to improve your intuition about how they work.

* Let's look at a few more examples of how these array layouts work to get them really grounded in your head.
* All of these examples will be using row major order, since that is the default of NumPy, and we won't be trying anything that changes it.
* I'm going to start with a 2-dimensional array, where the hundreds digit is the first coordinate, and the ones digit is the second coordinate.

In [ ]:
import numpy as np

x = np.array([[0, 1, 2, 3], [100, 101, 102, 103], [200, 201, 202, 203]])
x

array([[  0,   1,   2,   3],
       [100, 101, 102, 103],
       [200, 201, 202, 203]])

* So looking at how that is displayed now, if you see one of these numbers, you can tell where it came from in the array.
* To be even more explicit about how it is organized, let's look at one row at a time.

In [ ]:
x[0]

array([0, 1, 2, 3])

In [ ]:
x[1]

array([100, 101, 102, 103])

In [ ]:
x[2]

array([200, 201, 202, 203])

* Now, let's look at the layout of this array.
* There is a function called ravel that numpy has to see the contents of an array flattened into one dimensional.
* The word ravel is a verb meaning to become unwoven, untwisted, or unwound.
* So this function will remove the more complicated 2D structure.

In [ ]:
x_1d = np.ravel(x)
x_1d

array([  0,   1,   2,   3, 100, 101, 102, 103, 200, 201, 202, 203])

* One promise of this function is that it will make sure that the data is contiguous in memory, all in a row together, in the same order as we see it in the array.
* And it will do this sharing the memory of the original array if possible.
* We will get into the technical details of that in the next lesson.
* For now, the thing to know is that if the sharing works, you can edit the contents of one array from the other array, because their data is the same.

In [ ]:
x_1d[2] = 999
x

array([[  0,   1, 999,   3],
       [100, 101, 102, 103],
       [200, 201, 202, 203]])

* See how a value in the original array x changed when we changed a value in the raveled array?
* So there we can see that the order from the raveled array is the same as the order used by the two dimensional array, because we can see them sharing data.

* Let's look at another example, this time in 3D.
* For this example, I will start with the linear 1-dimensional array, and turn it a 3-dimensional array.

In [ ]:
y = np.arange(27)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

* The y array was initialized counting from zero, so you can relate the original position to the 3D view.
* The length of y is 27 which is 3 to the third power, so we can turn it into a 3 by 3 by 3 array with 3 dimensions.


In [ ]:
y = y.reshape((3, 3, 3))
y

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

* See how in this view, the values in y still count from zero, but with various sub arrays beginning and ending, adding a lot of punctuation between numbers.
* If you fix the first dimension's index to be zero, you will see the array with values from 0 to 8.

In [ ]:
y[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

* If you fix the first index to one, you will see the array with values from 9 to 17.

In [ ]:
y[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

* And if you fix the first index to two, you will see the array with values from 18 to 26.

In [ ]:
y[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

* Hopefully, this improves your intuition for how multi-dimensional arrays are laid out in memory.

**Code Notes:**
* The NumPy function [`numpy.ravel`](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html), referenced as `np.ravel`, returns a contiguous 1-dimensional view of the input array.
  * If possible, it returns a view of the input array, so the underlying data is shared.
  * We will learn more about views in the next lesson.