# Video: Splitting and Combining Different Arrays

This video shows how to divide arrays into smaller evenly sized arrays, and then recombine them.

In [ ]:
import numpy as np

In [ ]:
x = np.arange(24).reshape(4, 6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
np.hsplit(x, 3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])]

In [ ]:
np.vsplit(x, 2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [ ]:
np.hstack(np.hsplit(x, 3))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
np.vstack(np.vsplit(x, 2))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

**Code Notes:**
* The NumPy functions [numpy.hsplit](https://numpy.org/doc/stable/reference/generated/numpy.hsplit.html) and [numpy.vsplit](https://numpy.org/doc/stable/reference/generated/numpy.vsplit.html) will respectively split a 2-dimensional array horizontally or vertically.
  * These functions both return Python lists of the split out arrays.
  * Each of the split out arrays is a view into the original array.
  * See the documentation for the handling of other numbers of dimensions.
* The NumPy functions [numpy.hstack](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html) and [numpy.vstack](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html) will combine 2-dimensional arrays as if they were laid out horizontally or vertically next to each other.
  * These functions are like inverses to the corresponding split functions, but will return new arrays, not views back to the array before splitting.
  * See the documentation for the handling of other numbers of dimensions.
* [numpy.split](https://numpy.org/doc/stable/reference/generated/numpy.split.html) and [numpy.stack](https://numpy.org/doc/stable/reference/generated/numpy.stack.html) generalize these functions to more dimensions.