# Video: Slicing Arrays with Views

This video introduces slicing, a special way to index Python lists and NumPy arrays.
Slicing lets you concisely select a subset of a list as long as the entries are spaced evenly.
NumPy generalizes slicing support to allow creating views of sliced on multiple dimensions at once.

In [ ]:
import numpy as np

In [ ]:
x = list(range(20))
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
x[5:10]

[5, 6, 7, 8, 9]

In [ ]:
x[3:16:3]

[3, 6, 9, 12, 15]

SEQUENCE[START:END:STEP]

In [ ]:
print(range.__doc__)

range(stop) -> range object
range(start, stop[, step]) -> range object

Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
These are exactly the valid indices for a list of 4 elements.
When step is given, it specifies the increment (or decrement).


In [ ]:
x[10]

10

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
x[10]

10

In [ ]:
x[0:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
x[0:10:3]

[0, 3, 6, 9]

In [ ]:
x[:10:3]

[0, 3, 6, 9]

In [ ]:
x[15:]

[15, 16, 17, 18, 19]

In [ ]:
x[15::]

[15, 16, 17, 18, 19]

In [ ]:
x[::5]

[0, 5, 10, 15]

In [ ]:
x2 = np.array(x)
x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
x2[::5]

array([ 0,  5, 10, 15])

In [ ]:
x3 = x2.reshape(4, 5)
x3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
x3[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14]])

In [ ]:
x3[::2,1]

array([ 1, 11])

In [ ]:
x3[::2,1:2]

array([[ 1],
       [11]])

In [ ]:
x3.strides

(40, 8)

In [ ]:
x3[::2,::3].strides

(80, 24)

In [ ]:
x3[1,1]

6

In [ ]:
x3[1][1]

6