# Video: Seeing Array Views of Different Shapes

In this video, we will create array views matching the previous example, and show how changing one entry predictably makes changes visible in the other views.

* The first function that we will look at for making views will be reshape.
* Let us start with an array of 12 numbers like before.

In [ ]:
x_1d = np.arange(12)
x_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

* And let's make all the 2D arrays with all of that data.

In [ ]:
x_2d_choices = [x_1d.reshape(s_0, 12 // s_0) for s_0 in [1, 2, 3, 4, 6, 12]]
x_2d_choices

[array([[    0,     1,     2,     3,     4, 12345,     6,     7,     8,
             9,    10,    11]]),
 array([[    0,     1,     2,     3,     4, 12345],
        [    6,     7,     8,     9,    10,    11]]),
 array([[    0,     1,     2,     3],
        [    4, 12345,     6,     7],
        [    8,     9,    10,    11]]),
 array([[    0,     1,     2],
        [    3,     4, 12345],
        [    6,     7,     8],
        [    9,    10,    11]]),
 array([[    0,     1],
        [    2,     3],
        [    4, 12345],
        [    6,     7],
        [    8,     9],
        [   10,    11]]),
 array([[    0],
        [    1],
        [    2],
        [    3],
        [    4],
        [12345],
        [    6],
        [    7],
        [    8],
        [    9],
        [   10],
        [   11]])]

* If we change any of those arrays, then we will see it in all of those arrays.

In [ ]:
x_1d[5] = 12345
x_2d_choices

[array([[    0,     1,     2,     3,     4, 12345,     6,     7,     8,
             9,    10,    11]]),
 array([[    0,     1,     2,     3,     4, 12345],
        [    6,     7,     8,     9,    10,    11]]),
 array([[    0,     1,     2,     3],
        [    4, 12345,     6,     7],
        [    8,     9,    10,    11]]),
 array([[    0,     1,     2],
        [    3,     4, 12345],
        [    6,     7,     8],
        [    9,    10,    11]]),
 array([[    0,     1],
        [    2,     3],
        [    4, 12345],
        [    6,     7],
        [    8,     9],
        [   10,    11]]),
 array([[    0],
        [    1],
        [    2],
        [    3],
        [    4],
        [12345],
        [    6],
        [    7],
        [    8],
        [    9],
        [   10],
        [   11]])]

* See how changing the original 1D array changed the others?

* We can check if an array is a view by checking if the base attribute is None.

In [ ]:
[a.base for a in x_2d_choices]

[array([    0,     1,     2,     3,     4, 12345,     6,     7,     8,
            9,    10,    11]),
 array([    0,     1,     2,     3,     4, 12345,     6,     7,     8,
            9,    10,    11]),
 array([    0,     1,     2,     3,     4, 12345,     6,     7,     8,
            9,    10,    11]),
 array([    0,     1,     2,     3,     4, 12345,     6,     7,     8,
            9,    10,    11]),
 array([    0,     1,     2,     3,     4, 12345,     6,     7,     8,
            9,    10,    11]),
 array([    0,     1,     2,     3,     4, 12345,     6,     7,     8,
            9,    10,    11])]

* The base attribute refers to the original array for views, and is None otherwise.
* You can confirm if a particular array is the original using the id function.

In [ ]:
id(x_1d)

137930052599600

In [ ]:
[id(a.base) for a in x_2d_choices]

[137930052599600,
 137930052599600,
 137930052599600,
 137930052599600,
 137930052599600,
 137930052599600]

* This is most likely done while debugging.
* You generally won't need to go looking for the original array.
* Most likely, you'll have it easily available already, but the real question you'll be checking is whether it used a view or not.

**Code Notes:**
* The NumPy function [`numpy.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html), referenced as `np.reshape`, returns a new array with the same data and a specified shape.
  * `reshape` returns a view whenever possible.
