# Video: Broadcasting Views

This video shows off the views used for broadcasting.
You will not need to explicitly use them very often, but understanding how they work will help you make good use of broadcasting.


* Last week, we saw broadcasting as a way that NumPy can operate with arrays of different dimensions in sensible ways.
* How does that work?

In [ ]:
import numpy as np

* Let's start off with a one-dimensional array x of three elements.

In [ ]:
x = np.array([0, 1, 2])
x

array([0, 1, 2])

* And a 2-dimensional array with three rows and one column.

In [ ]:
y = np.array([[0], [1], [2]])
y

array([[0],
       [1],
       [2]])

* Since x is one dimensional, it will be extended to two dimensions, making it one row of 3 columns.

In [ ]:
x.shape

(3,)

* And y already is 3 rows and 1 column.

In [ ]:
y.shape

(3, 1)

* When they are broadcast together, the result will have 3 rows and 3 columns.
* How will x and y be transformed for that computation?

In [ ]:
np.broadcast_to(x, (3, 3))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
np.broadcast_to(y, (3, 3))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

* These are both views, so you can guess that something is happening with the strides.

In [ ]:
x.strides

(8,)

* The original x array had a simple stride of 8, because the values in x take 8 bytes.

In [ ]:
np.broadcast_to(x, (3, 3)).strides

(0, 8)

* The broadcast view of x has a stride of zero for the new axis.
* What does a stride of zero mean? It means that when moving along that axis, the memory location has zero added, so the memory location does not change.
* Since the memory location does not change, the same data is read.
* So it looks like the data is copied along that axis.
* And if we look at the broadcast view of x again, each row is the same.

In [ ]:
np.broadcast_to(x, (3, 3))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

* What about y?
* y already had two dimensions.

In [ ]:
y.strides

(8, 8)

* Looking at the strides of y, they are the same.
* Is that weird?
* Not really -- when we first talked about strides, we said the last stride for a contiguous array is the element size.
* But this array has length 1 on that axis, so it never gets used.
* Let's look at the strides of the broadcast view of y.

In [ ]:
np.broadcast_to(y, (3, 3)).strides

(8, 0)

* We see a zero stride again for the axis where the data will be repeated.
* If you look into more examples of broadcasting, you will always see the stride set to zero for the axes where the data is repeated since the zero stride means the same data is read again.
* These views let broadcasting work as if both arrays were both expanded and copied to be the final output size, but without any of the overhead making those bigger copies of the arrays.