# Video: Broadcasting Views

This video shows off the views used for broadcasting.
You will not need to explicitly use them very often, but understanding how they work will help you make good use of broadcasting.


In [78]:
import numpy as np

In [79]:
x = np.array([0, 1, 2])
x

array([0, 1, 2])

In [80]:
y = np.array([[0], [1], [2]])
y

array([[0],
       [1],
       [2]])

In [81]:
x.shape

(3,)

In [82]:
y.shape

(3, 1)

In [83]:
np.broadcast_to(x, (3, 3))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [84]:
np.broadcast_to(y, (3, 3))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [85]:
x.strides

(8,)

In [86]:
np.broadcast_to(x, (3, 3)).strides

(0, 8)

In [87]:
np.broadcast_to(x, (3, 3))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [88]:
y.strides

(8, 8)

In [89]:
np.broadcast_to(y, (3, 3)).strides

(8, 0)