# Video: Splitting and Combining Different Arrays

This video shows how to divide arrays into smaller evenly sized arrays, and then recombine them.

* NumPy has a few functions to split up arrays into evenly sized smaller arrays.
* If this was a computer science class, we might use this for a recursive algorithm analyzing the array, or for matrix multiplication.
* If we were analyzing an image, we might want to analyze different areas separately.
* For data science, we might want to split the data for cross-validation to make sure we are building a reliable model.

In [ ]:
import numpy as np

* Starting with our usual array of integers to poke at views...

In [ ]:
x = np.arange(24).reshape(4, 6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

* hsplit will split a 2-dimensional array horizontally, dividing the columns into different arrays.

In [ ]:
np.hsplit(x, 3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])]

* vsplit will split a 2-dimensional array vertically, dividing the rows into different arrays.

In [ ]:
np.vsplit(x, 2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

* Both hsplit and vsplit return Python lists of the new arrays.
* And all those new arrays are views into the old array.
* You could create these arrays using slicing, using the slices to restrict the columns or rows selected, but these functions are more convenient if they match what you want.
* Both have the option to control the split points more specifically than evenly dividing the rows or columns if you want.

* hsplit and vsplit each have a kind of inverse, hstack and vstack respectively, that combines arrays together.

In [ ]:
np.hstack(np.hsplit(x, 3))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
np.vstack(np.vsplit(x, 2))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

* Neither hstack nor vstack returns a view.
* Returning a view generally will not be feasible, since that would require the inputs to be views of the same original array, in the order they were split apart with no omissions.
* If you know that much, you probably can make a view from the original array.

* If you want or need to split and combine arrays with higher dimensions, there are split and stack functions that are more general and will let you specify the axis to split and combine along.

**Code Notes:**
* The NumPy functions [numpy.hsplit](https://numpy.org/doc/stable/reference/generated/numpy.hsplit.html) and [numpy.vsplit](https://numpy.org/doc/stable/reference/generated/numpy.vsplit.html) will respectively split a 2-dimensional array horizontally or vertically.
  * These functions both return Python lists of the split out arrays.
  * Each of the split out arrays is a view into the original array.
  * See the documentation for the handling of other numbers of dimensions.
* The NumPy functions [numpy.hstack](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html) and [numpy.vstack](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html) will combine 2-dimensional arrays as if they were laid out horizontally or vertically next to each other.
  * These functions are like inverses to the corresponding split functions, but will return new arrays, not views back to the array before splitting.
  * See the documentation for the handling of other numbers of dimensions.
* [numpy.split](https://numpy.org/doc/stable/reference/generated/numpy.split.html) and [numpy.stack](https://numpy.org/doc/stable/reference/generated/numpy.stack.html) generalize these functions to more dimensions.