# Video: Slicing Arrays with Views

This video introduces slicing, a special way to index Python lists and NumPy arrays.
Slicing lets you concisely select a subset of a list as long as the entries are spaced evenly.
NumPy generalizes slicing support to allow creating views of sliced on multiple dimensions at once.

Script:
* Slicing is a Python feature that we previously skipped.
* Let me give you a couple examples first, then I'll explain how it works.

In [ ]:
import numpy as np

In [ ]:
x = list(range(20))
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

Script:
* I am starting with a list with twenty numbers, zero through nineteen.
* Like with the view examples, I am starting with a list where the indices and values match, so you can easily see which positions in the list were selected.

In [ ]:
x[5:10]

[5, 6, 7, 8, 9]

Script:
* That slice takes entries in the list, starting at 5, and stopping before 10.
* So five through nine.

In [ ]:
x[3:16:3]

[3, 6, 9, 12, 15]

Script:
* That slice starts at index 3, and takes every third entry before index 16.
* The general form looks like this.

SEQUENCE[START:END:STEP]

Script:
* The sequence can be a Python builtin list or tuple, or a similar object like a NumPy array.
* The start is the first index selected.
* Then the step is added to get new indexes.
* And the slice stops before the end index.
* This is exactly like how the range function works.

In [ ]:
print(range.__doc__)

range(stop) -> range object
range(start, stop[, step]) -> range object

Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
These are exactly the valid indices for a list of 4 elements.
When step is given, it specifies the increment (or decrement).


Script:
* Slices take the same input numbers as the range object, but separated by colons, and they go between the square brackets of the indexing notation.
* The one difference from the range function is that the one number handling is different.
* If you index with one number, you just get that entry from the sequence back.

In [ ]:
x[10]

10

Script:
* If you call range with one number, you get a sequence from zero up to but not including that number.

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Script:
* Another way to think of it, that is more precise, is that slices and the range like behavior is invoked when you use the colon in the index.
* No colon, no slice, no range like behavior.

In [ ]:
x[10]

10

In [ ]:
x[0:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
x[0:10:3]

[0, 3, 6, 9]

Script:
* Once you add the colons, you can leave out some of the numbers and reasonable defaults will be used.
* The default start is zero, for the beginning of the array.
* The default end is the length of the sequence, or that dimension if it is a NumPy array.
* And the default step size is one.

In [ ]:
x[:10:3]

[0, 3, 6, 9]

Script:
* This one starts at the beginning and goes up to but not including ten, stepping by three.

In [ ]:
x[15:]

[15, 16, 17, 18, 19]

In [ ]:
x[15::]

[15, 16, 17, 18, 19]

Script:
* Both of those start at index 15 and go to the end.

In [ ]:
x[::5]

[0, 5, 10, 15]

Script:
* And that one starts at the beginning and goes to the end, stepping by five.
* When slicing a list, a new list is returned.
* When slicing a NumPy array, a view is returned.

In [ ]:
x2 = np.array(x)
x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
x2[::5]

array([ 0,  5, 10, 15])

Script:
* Slicing NumPy arrays is not just limited to one-dimensional arrays.
* You can slice multiple dimensions at once by separating them with commas, just like if you were reading an individual value and specifying its coordinates.

In [ ]:
x3 = x2.reshape(4, 5)
x3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
x3[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14]])

Script:
* You can also mix slicing and specific index values.

In [ ]:
x3[::2,1]

array([ 1, 11])

Script:
* Remember, the dimension of the resulting array will drop for each axis with a specific value chosen.
* If you don't want that, you can specify a slice of just one value.

In [ ]:
x3[::2,1:2]

array([[ 1],
       [11]])

Script:
* One brief comment on how array slicing works.
* This works because however you setup the slices, the indices chosen will always be at fixed intervals from the step size.
* So if you compare the strides, you can see that step size being multiplied there.

In [ ]:
x3.strides

(40, 8)

In [ ]:
x3[::2,::3].strides

(80, 24)

Script:
* Comparing those strides, you can see the stride length is multiplied by the step size.
* There are a few other advanced ways to index arrays, but they usually don't work as views because they don't have that fixed size to make a new stride.
* Without the fixed size, you can't have a fixed stride along each axis, and the views won't work.
* One final note on efficiency of arrays and views.
* You've seen array indexing giving all the coordinates at once.

In [ ]:
x3[1,1]

6

Script:
* And you've seen array indexing where you give one coordinate, get a sub array, and then index that.

In [ ]:
x3[1][1]

6

Script:
* The first version giving all the coordinates at once is generally more efficient, because the sub array is not created and abandoned in the middle.
* Certain access patterns can be made faster, if you reuse the subarray from the earlier indexing.
* But unless you are making the effort to get that speedup, just pass all the indexes at once.