# Video: Handling Arrays of Different Shapes

This video introduces NumPy's handling of arrays with different shapes.
Combining arrays with individual scalars have a simple intuitive behavior.
Broadcasting generalizes that behavior in a powerful way.

In [ ]:
import numpy as np

x = np.array([[0, 1, 2, 3, 4, 5]])
x

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
x + 10

array([[10, 11, 12, 13, 14]])

In [ ]:
y = np.array([[0], [100], [200], [300], [400]])
y

array([[  0],
       [100],
       [200],
       [300],
       [400]])

In [ ]:
x + y

array([[  0,   1,   2,   3,   4,   5],
       [100, 101, 102, 103, 104, 105],
       [200, 201, 202, 203, 204, 205],
       [300, 301, 302, 303, 304, 305],
       [400, 401, 402, 403, 404, 405]])

In [ ]:
x.shape

(1, 6)

In [ ]:
y.shape

(5, 1)

In [ ]:
(x + y).shape

(5, 6)

In [ ]:
x

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
y

array([[  0],
       [100],
       [200],
       [300],
       [400]])

In [ ]:
x + y

array([[  0,   1,   2,   3,   4,   5],
       [100, 101, 102, 103, 104, 105],
       [200, 201, 202, 203, 204, 205],
       [300, 301, 302, 303, 304, 305],
       [400, 401, 402, 403, 404, 405]])