# Video: Making a Universal Function

This video shows an example of making and testing a universal function to illustrate how NumPy builds up broad array and broadcast support from a simple function.

In [ ]:
import numpy as np

def my_add(x, y):
    return x + y


In [ ]:
universal_my_add = np.frompyfunc(my_add, 2, 1)

In [ ]:
x = np.array([[0, 5, 10], [3, 7, 11]])
x

array([[ 0,  5, 10],
       [ 3,  7, 11]])

In [ ]:
universal_my_add(x, x)

array([[0, 10, 20],
       [6, 14, 22]], dtype=object)

In [ ]:
universal_my_add.reduce(x)

array([3, 12, 21], dtype=object)

In [ ]:
universal_my_add.reduce(x, axis=1)

array([15, 21], dtype=object)

In [ ]:
vectorized_my_add = np.vectorize(my_add, otypes=["float64"])
vectorized_my_add

In [ ]:
vectorized_my_add(x, x)

array([[ 0., 10., 20.],
       [ 6., 14., 22.]])

In [ ]:
vectorized_my_add([[1, 2, 3]], [[100], [200], [300]])

array([[101., 102., 103.],
       [201., 202., 203.],
       [301., 302., 303.]])