# Video: NumPy as an Array Calculator

This video will show off NumPy arrays to perform bulk calculations quickly, similar to using Python as a calculator in week 1, but with thousands or millions of numbers at once.
Basic math operations and NumPy's large library of functions will both be highlighted.

In [ ]:
import numpy as np

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
y = np.array([[7, 8, 9], [10, 11, 12]])
y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
x + y

array([[ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
x - y

array([[-6, -6, -6],
       [-6, -6, -6]])

In [ ]:
x * y

array([[ 7, 16, 27],
       [40, 55, 72]])

In [ ]:
x / y

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [ ]:
x // y

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.sin(x)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])