# Video: Creating Arrays of Zeros and Other Constants

This video give examples of creating arrays of zeros which are convenient as a blank slate to start your calculations from scratch.
Examples of creating arrays of all ones and other constants are also included.

Script:
* We just talked about making a NumPy array from data that you already had in some Python data structure.
* Now, let's make some empty or blank arrays, to start something new from scratch.

In [ ]:
import numpy as np

Script:
* The Numpy zeros function will make a new NumPy array full of zeros.

In [ ]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Script:
* The main argument is how big it should be.
* If you pass in an integer, like I just did, then you will get a one dimensional array with that length.
* If you pass in a tuple, that will be the length.

In [ ]:
z = np.zeros((2, 5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Script:
* As you can probably guess from the decimal points in that display, numpy dot zeros defaults to floating point values.
* Let's spot check which type was used.

In [ ]:
z.dtype

dtype('float64')

Script:
* So the default is float64.
* You can override the data type by using the optional dtype argument.

In [ ]:
z = np.zeros((2, 5), dtype="int32")
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

Script:
* Conveniently, it showed the dtype too.
* I believe that will always happen if the data type is not float64 or int64, to call attention to non-default types.
* Almost every NumPy function has that dtype parameter, so it is easy to change the output data type.
* You will mostly use the dtype parameter when the NumPy function does not take any arrays as inputs.
* NumPy functions taking arrays as inputs generally use the data types of their inputs.
* If you want to match the size and data type of an existing array, there is another Numpy function zeros_like that will do that.


In [ ]:
z2 = np.zeros_like(z)
z2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

Script:
* Zeros and zeros_like are the most common functions to create a new array.
* There are also functions called ones and ones_like.
* These are just like zeros but they fill their output with ones instead of zeros.

In [ ]:
o3 = np.ones((2, 5))
o3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Script:
* ones and ones like also default to float64.
* And two more functions full and full like, that take in one more argument that is filled in.

In [ ]:
f = np.full((2, 5), 3)
f

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

Script:
* Numpy full and full like pick their data type based on the value you provide.
* If the value is a floating point number, it will be float64.
* If the value is an integer, it will be int64.
* You could avoid using full and full_like by using ones and ones_like and multiplying them by the value, but that is inefficient in two ways.
* First, you have to write more code, and you have to think more about the data types to set them properly in the ones or ones like call, where full or full_like would pick based on the value provided.
* Second, you are asking your program to create an array of ones, multiplying it by the value to make a second array, then throwing away the first one.
* If you want an array full of a value besides zero or one, just use full and skip the extra work.
* Now you can create a new array initialized to the value of your choice, and you know a few different functions to do so clearly and concisely.