# Video: Creating a NumPy Array from Python Sequences

This video gives examples of creating NumPy arrays from Python sequences.
This is the simplest way to take advantage of NumPy efficiency in an existing Python program that already has data.
We will look at what data types and shapes NumPy picks based on different inputs, and discuss the implied reasons.


In [ ]:
import numpy as np

In [ ]:
my_data_array = np.array([1, 2, 3])
my_data_array

array([1, 2, 3])

In [ ]:
my_data_array.dtype

dtype('int64')

In [ ]:
my_data_array.shape

(3,)

In [ ]:
my_data_array[0]

1

In [ ]:
my_data_array[1]

2

In [ ]:
my_data_array[2]

3

In [ ]:
my_data_array[-1]

3

In [ ]:
my_data_array[-2]

2

In [ ]:
my_data_array[-3]

1

In [ ]:
my_data_array = np.array([1.0, 2.0, 3.0])
my_data_array

array([1., 2., 3.])

In [ ]:
my_data_array.dtype

dtype('float64')

In [ ]:
my_data_array = np.array([1, 2, 3.0])
my_data_array

array([1., 2., 3.])

In [ ]:
my_data_array.dtype

dtype('float64')

In [ ]:
my_data_array = np.array([[1, 2], [3, 4], [5, 6]])
my_data_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
my_data_array.shape

(3, 2)

In [ ]:
 my_data_list = [[1, 2], [3, 4], [5, 6]]
 my_data_list

[[1, 2], [3, 4], [5, 6]]

In [ ]:
my_data_list[0]

[1, 2]

In [ ]:
my_data_list[1]

[3, 4]

In [ ]:
my_data_list[2]

[5, 6]

In [ ]:
my_data_array[0]

array([1, 2])

In [ ]:
my_data_array[1]

array([3, 4])

In [ ]:
my_data_array[2]

array([5, 6])

In [ ]:
np.array([[1, 2], [3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
my_data_array = np.asarray([[1, 2], [3, 4], [5, 6]])
my_data_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
id(my_data_array)

136263992969712

In [ ]:
my_data_array_2 = np.array(my_data_array)
id(my_data_array_2)

136263992878032

In [ ]:
my_data_array_3 = np.asarray(my_data_array)
id(my_data_array_3)

136263992969712

In [ ]:
np.array([1.2 for i in range(10)])

array([1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2])

In [ ]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.array(i for i in range(10))

array(<generator object <genexpr> at 0x7bee6eeea3b0>, dtype=object)

In [ ]:
np.fromiter((i for i in range(10)), dtype=np.dtype("float64"))

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])