# Video: Creating Arrays of Zeros and Other Constants

This video give examples of creating arrays of zeros which are convenient as a blank slate to start your calculations from scratch.
Examples of creating arrays of all ones and other constants are also included.

In [ ]:
import numpy as np

In [ ]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
z = np.zeros((2, 5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
z.dtype

dtype('float64')

In [ ]:
z = np.zeros((2, 5), dtype="int32")
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [ ]:
z2 = np.zeros_like(z)
z2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [ ]:
o3 = np.ones((2, 5))
o3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
f = np.full((2, 5), 3)
f

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])