# Video: Reducing Arrays

This video gives examples of using NumPy to reduce arrays to smaller summaries or statistics of the data.

In [ ]:
x = np.array([[1, 3, 6], [2, 3, 5]])
x

array([[1, 3, 6],
       [2, 3, 5]])

In [ ]:
np.sum(x)

20

In [ ]:
np.mean(x)

3.3333333333333335

In [ ]:
np.max(x)

6

In [ ]:
x

array([[1, 3, 6],
       [2, 3, 5]])

In [ ]:
np.sum(x, axis=0)

array([ 3,  6, 11])

In [ ]:
np.sum(x, axis=1)

array([10, 10])

In [ ]:
x

array([[1, 3, 6],
       [2, 3, 5]])

In [ ]:
x1 = np.sum(x, axis=1, keepdims=True)
x1

array([[10],
       [10]])

In [ ]:
x1.shape

(2, 1)

In [ ]:
np.sum(x)

20

In [ ]:
x.sum()

20